#ifndef ERROR_CODES_H
#define ERROR_CODES_H

typedef enum
{
    SUCCESS = 0,
    FILE_NOT_FOUND,
    FILE_HAS_NO_CONTENT,
    NULL_POINTER_ERROR,
    INVALID_NUM_SAMPLES_ERROR,
    INVALID_TAPS_ERROR,
    TAPS_EXCEEDS_SAMPLES_ERROR,
    FILE_WRITE_ERROR,
    UNKNOWN_FILTER_TYPE,
    INVALID_ARGUMENT
} ErrorCode;

#endif